title: Site

options: 
  changeTitle: false
  changeStatus: false
  changeTemplate: false
  delete: false
  duplicate: false
  move: false

tabs: 
  writing: 
    label: Main Site
    icon: book
    columns:
      left: 
        width: 2/3
        sections:
          main: 
            type: pages
            label: Pages
            status: listed
            info: "{{ page.slug }}"
          drafts:
            type: pages
            label: Not Live
            status: drafts
            templates: 
              - books
            image:
              back: green
              color: white
              cover: true
      right:
        width: 1/3
        fields: 
          landing: 
            label: Landing
            type: files
            uploads: false
            multiple: false
            layout: cardlets
            info: "alt: {{ file.alt }}"
            template: landing
          

            
        


        



  
    

