# name: Deploy to Digital Ocean Server

# on:
#   push:
#     branches:
#       - main  # Or your default branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Deploy to Server
#       uses: appleboy/ssh-action@v1.2.2
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USER }}
#         key: ${{ secrets.DEPLOY_KEY }}
#         script: |
#           cd /var/www/zavizavizavi.com/html
#           git pull origin main